### ISSUE TITLE
Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by blopez2010** [git-time-metric/gtm#57]
Hello,

This error is constantly being written in the console on my Mac.

shell.ts:541Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
    at /Users/blopez/.vscode/extensions/s3ramsay.vscode-gtm-0.1.2/out/src/extension.js:49:88
    at e.invoke (/Users/blopez/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:31992)
    at e.fire (/Users/blopez/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:5:8945)
    at t.$acceptActiveEditorAndVisibleEditors (/Users/blopez/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:11:7855)
    at t.e.handle (/Users/blopez/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:10:4203)
    at s (/Users/blopez/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:7:11178)
    at p (/Users/blopez/Downloads/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:7:11855)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by mschenk42** [comment]
I believe this is the same issue https://github.com/nexus-uw/vscode-gtm/issues/12.  The author is currently working on a fix. Please share any comments within that repos issues.
